image: registry.gitlab.com/csprenger/docker-age-ci:latest

stages:
    - build
    - test

variables:
    ARTIFACTS_SUBDIR:   build/artifacts
    ARTIFACTS_DIR:      ${CI_PROJECT_DIR}/${ARTIFACTS_SUBDIR}
    ARTIFACTS_DIR_TEST: ${ARTIFACTS_DIR}/test
    ARTIFACTS_DIR_WASM: ${ARTIFACTS_DIR_WASM}/wasm
    TEST_SUBDIR: test



############################################################
##
##   build
##
############################################################

.build: &build-qt-preset
    stage: build
    script:
        - "DIR=`mktemp -d` && cd $DIR"
        - "qmake ${QMAKE_ARGUMENTS} ${CI_PROJECT_DIR}/build/qmake/age.pro"
        - make -j 4
        - mkdir -p ${ARTIFACTS_DIR_TEST}
        - cp age_qt_emu_test/age_qt_emu_test ${ARTIFACTS_DIR_TEST}
    artifacts:
        expire_in: 30 mins
        paths:
            - ${ARTIFACTS_SUBDIR}/
    tags:
        - linux

build-qt-debug:
    <<: *build-qt-preset
    variables:
        QMAKE_ARGUMENTS: "CONFIG+=debug"

build-qt-release:
    <<: *build-qt-preset
    variables:
        QMAKE_ARGUMENTS: "CONFIG+=release"


build-wasm:
    stage: build
    image: registry.gitlab.com/csprenger/docker-age-ci/wasm:latest
    script:
        - source ${REPO_EMSDK}/emsdk_env.sh
        - ${CI_PROJECT_DIR}/build/wasm/run_cmake.sh
    artifacts:
        expire_in: 30 mins
        paths:
            - artifacts/wasm/
    tags:
        - linux



############################################################
##
##   test
##
############################################################

.test-release: &test-preset-release
    stage: test
    dependencies:
        - build-qt-release
    tags:
        - linux

.test-debug: &test-preset-debug
    stage: test
    dependencies:
        - build-qt-debug
    tags:
        - linux


test-mooneye-release:
    <<: *test-preset-release
    script:
        - sh ${TEST_SUBDIR}/ci_run_mooneye_tests.sh

test-mooneye-debug:
    <<: *test-preset-debug
    script:
        - sh ${TEST_SUBDIR}/ci_run_mooneye_tests.sh


test-gambatte-release:
    <<: *test-preset-release
    script:
        - sh ${TEST_SUBDIR}/ci_run_gambatte_tests.sh

# gambatte tests run for longer than 10 minutes with the debug build
#test-gambatte-debug:
#    <<: *test-preset-debug
#    script:
#        - sh ${TEST_SUBDIR}/ci_run_gambatte_tests.sh

