image: registry.gitlab.com/csprenger/docker-age-ci:latest

stages:
    - build
    - test

variables:
    TEST_SUBDIR: testing
    TEST_DIR:    ${CI_PROJECT_DIR}/${TEST_SUBDIR}
    APP_NAME:    age_emulator_test
    TEST_APP:    ${TEST_DIR}/${APP_NAME}



############################################################
##
##   build
##
############################################################

.build: &build_preset
    stage: build
    script:
        - "DIR=`mktemp -d` && cd $DIR"
        - "qmake ${QMAKE_ARGUMENTS} ${CI_PROJECT_DIR}/src/age.pro"
        - make -j 4
        - cp age_emulator_test/${APP_NAME} ${TEST_DIR}
    artifacts:
        expire_in: 30 mins
        paths:
            - ${TEST_SUBDIR}/
    tags:
        - linux

build_debug:
    <<: *build_preset
    variables:
        QMAKE_ARGUMENTS: "CONFIG+=debug"

build_release:
    <<: *build_preset
    variables:
        QMAKE_ARGUMENTS: "CONFIG+=release"



############################################################
##
##   test
##
############################################################

.test: &test_preset
    stage: test
    script:
        - ${TEST_APP} ${TEST_TYPE} --ignore-list ${TEST_DIR}/tests_to_ignore.txt ${TEST_PATH}
    tags:
        - linux

.test_mooneye: &mooneye_test_preset
    <<: *test_preset
    variables:
        TEST_TYPE: "--type mooneye"
        TEST_PATH: ${GB_REPO_MOONEYE_GB}/tests/build

test_mooneye_debug
    <<: *mooneye_test_preset
    dependencies:
        - build_debug

test_mooneye_release
    <<: *mooneye_test_preset
    dependencies:
        - build_release
