image: registry.gitlab.com/csprenger/docker-age-ci:latest

stages:
    - build
    - test

variables:
    ARTIFACTS:      build/ci_artifacts
    ARTIFACTS_TEST: ${ARTIFACTS}/test
    ARTIFACTS_WASM: ${ARTIFACTS}/wasm



############################################################
##
##   build
##
############################################################

.build: &build-preset
    stage: build
    before_script:
        - mkdir -p ${ARTIFACTS_TEST}
        - mkdir -p ${ARTIFACTS_WASM}
    artifacts:
        expire_in: 30 mins
        untracked: true
    tags:
        - linux


.build-qt: &build-qt-preset
    <<: *build-preset
    script:
        - "DIR=`mktemp -d` && cd $DIR"
        - "qmake ${QMAKE_ARGUMENTS} ${CI_PROJECT_DIR}/build/qmake/age.pro"
        - make -j 4
        - cp age_qt_emu_test/age_qt_emu_test ${CI_PROJECT_DIR}/${ARTIFACTS_TEST}

build-qt-debug:
    <<: *build-qt-preset
    variables:
        QMAKE_ARGUMENTS: "CONFIG+=debug"

build-qt-release:
    <<: *build-qt-preset
    variables:
        QMAKE_ARGUMENTS: "CONFIG+=release"


build-wasm:
    <<: *build-preset
    image: registry.gitlab.com/csprenger/docker-age-ci/wasm:latest
    script:
        - source ${REPO_EMSDK}/emsdk_env.sh
        - ${CI_PROJECT_DIR}/build/wasm/run_cmake.sh



############################################################
##
##   test
##
############################################################

.test-release: &test-preset-release
    stage: test
    dependencies:
        - build-qt-release
    tags:
        - linux

.test-debug: &test-preset-debug
    stage: test
    dependencies:
        - build-qt-debug
    tags:
        - linux


test-mooneye-release:
    <<: *test-preset-release
    script:
        - sh test/ci_run_mooneye_tests.sh

test-mooneye-debug:
    <<: *test-preset-debug
    script:
        - sh test/ci_run_mooneye_tests.sh


test-gambatte-release:
    <<: *test-preset-release
    script:
        - sh test/ci_run_gambatte_tests.sh

# gambatte tests run for longer than 10 minutes with the debug build
#test-gambatte-debug:
#    <<: *test-preset-debug
#    script:
#        - sh test/ci_run_gambatte_tests.sh

