image: registry.gitlab.com/csprenger/docker-age-ci:latest

stages:
    - build
    - test

variables:
    TEST_SUBDIR: testing
    TEST_DIR:    ${CI_PROJECT_DIR}/${TEST_SUBDIR}
    APP_NAME:    age_emulator_test
    TEST_APP:    ${TEST_DIR}/${APP_NAME}



############################################################
##
##   build
##
############################################################

.build: &build_preset
    stage: build
    script:
        - "DIR=`mktemp -d` && cd $DIR"
        - "qmake ${QMAKE_ARGUMENTS} ${CI_PROJECT_DIR}/src/age.pro"
        - make -j 4
        - ls -lsah age_emulator_test
        - cp age_emulator_test/${APP_NAME} ${TEST_DIR}
    artifacts:
        expire_in: 30 mins
        paths:
            - ${TEST_SUBDIR}/
    tags:
        - linux

build_debug:
    <<: *build_preset
    variables:
        QMAKE_ARGUMENTS: "CONFIG+=debug"

build_release:
    <<: *build_preset
    variables:
        QMAKE_ARGUMENTS: "CONFIG+=release"
