image: registry.gitlab.com/csprenger/docker-age-ci:latest

stages:
    - build
    - test

variables:
    TEST_SUBDIR: test



############################################################
##
##   build
##
############################################################

.build: &build_preset
    stage: build
    script:
        - "DIR=`mktemp -d` && cd $DIR"
        - "qmake ${QMAKE_ARGUMENTS} ${CI_PROJECT_DIR}/src/age.pro"
        - make -j 4
        - cp age_emulator_test/age_emulator_test ${CI_PROJECT_DIR}/${TEST_SUBDIR}
    artifacts:
        expire_in: 30 mins
        paths:
            - ${TEST_SUBDIR}/
    tags:
        - linux


build_debug:
    <<: *build_preset
    variables:
        QMAKE_ARGUMENTS: "CONFIG+=debug"

build_release:
    <<: *build_preset
    variables:
        QMAKE_ARGUMENTS: "CONFIG+=release"



############################################################
##
##   test
##
############################################################

.test_release: &test_preset_release
    stage: test
    dependencies:
        - build_release
    tags:
        - linux

.test_debug: &test_preset_debug
    stage: test
    dependencies:
        - build_debug
    tags:
        - linux


test_mooneye_release:
    <<: *test_preset_release
    script:
        - sh ${TEST_SUBDIR}/ci_run_mooneye_tests.sh

test_mooneye_debug:
    <<: *test_preset_debug
    script:
        - sh ${TEST_SUBDIR}/ci_run_mooneye_tests.sh


test_gambatte_release:
    <<: *test_preset_release
    script:
        - sh ${TEST_SUBDIR}/ci_run_gambatte_tests.sh

# gambatte tests run for longer than 10 minutes with the debug build
#test_gambatte_debug:
#    <<: *test_preset_debug
#    script:
#        - sh ${TEST_SUBDIR}/ci_run_gambatte_tests.sh

