name: AGE CI

on: [push, workflow_dispatch]

env:
  ARTIFACT_PATH: build/artifacts

jobs:

  ###############################################################################
  ##
  ##   build
  ##
  ###############################################################################

  build-qt:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/jurplel/install-qt-action
      - uses: jurplel/install-qt-action@v3
        with:
          # for a list of available modules see:
          # https://ddalcino.github.io/aqt-list-server/
          modules: 'qtmultimedia'
          version: '6.5.*'
          cache: true
      - uses: actions/checkout@v4
      - run: build/age_ci.sh build-qt Release
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ github.job }}
          path: ${{ env.ARTIFACT_PATH }}

  build-gtest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: build/age_ci.sh build-gtest Debug
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ github.job }}
          path: ${{ env.ARTIFACT_PATH }}

  build-test-runner:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: build/age_ci.sh build-test-runner Release
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ github.job }}
          path: ${{ env.ARTIFACT_PATH }}

  build-wasm:
    runs-on: ubuntu-22.04
    container:
      image: emscripten/emsdk:3.1.41
    steps:
      - uses: actions/checkout@v4
      - run: build/age_ci.sh build-wasm Release
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ github.job }}
          path: ${{ env.ARTIFACT_PATH }}


  ###############################################################################
  ##
  ##   test
  ##
  ###############################################################################

  run-gtest:
    runs-on: ubuntu-22.04
    needs: [ build-gtest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: artifact-build-gtest
          path: ${{ env.ARTIFACT_PATH }}
      - run: build/age_ci.sh run-gtest

  run-test-roms:
    runs-on: ubuntu-22.04
    needs: [ build-test-runner ]
    strategy:
      fail-fast: false
      matrix:
        test-suite:
          - acid2
          - age
          - blargg
          - little-things
          - gambatte
          - gbmicrotest
          - mealybug
          - mooneye
          - mooneye-wilbertpol
          - rtc3test
          - same-suite
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: artifact-build-test-runner
          path: ${{ env.ARTIFACT_PATH }}
      - run: build/age_ci.sh run-tests age
