name: AGE CI

on: push

env:
  ARTIFACT_NAME: age-artifacts
  ARTIFACT_PATH: artifacts

jobs:


  build-qt:
    name: build Qt applications
    runs-on: ubuntu-latest
    steps:
      # https://github.com/jurplel/install-qt-action
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache-5.12.8

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.8'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      # libQt5Multimedia requires libpulse
      - name: install libpulse
        run: |
          sudo apt-get update
          sudo apt-get install libpulse-dev

      - name: checkout code
        uses: actions/checkout@v2

      - name: build AGE
        run: build/age_ci.sh qt release

      - name: upload Qt artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

  build-wasm:
    name: build WebAssembly binaries
    runs-on: ubuntu-latest
    container:
      image: trzeci/emscripten:1.39.17-upstream
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: build binaries
        run: build/age_ci.sh wasm Release

      - name: upload WebAssembly artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}


  build-js:
    name: build Web App
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: build Web App
        run: build/age_ci.sh js build --progress=false --base-href /AGE/

      - name: upload JavaScript artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
